### PR TITLE
Assert the proper status code for PUT

### PR DESCRIPTION
**Pull request by untitaker**
See https://tools.ietf.org/html/rfc7231#section-4.3.4

Money quote:

```
If the target resource does not have a current representation and the
PUT successfully creates one, then the origin server MUST inform the
user agent by sending a 201 (Created) response.  If the target
resource does have a current representation and that representation
is successfully modified in accordance with the state of the enclosed
representation, then the origin server MUST send either a 200 (OK) or
a 204 (No Content) response to indicate successful completion of the
request.
```

### CODE REVIEW

**Comment by untitaker** [comment]
There are more instances in the code where this is a problem, will fix all of them eventually.

EDIT: Done

**Comment by raucao** [comment]
It's a MUST in the spec, but in real-world implementations of both servers and clients it's basically treated as a SHOULD and most programs send and accept 200s. If the storage backend doesn't inform your middleware, then it can be expensive to look it up first.

How about making it a warning instead of a failure (similar to how we treat content types)?

**Comment by untitaker** [comment]
I agree that nobody would care about this part. Warning sounds fine, but then I'd propose that warnings are fatal by default as well.

**Comment by untitaker** [comment]
I.e. you specifically need to opt out of a spec violation instead of opt in. Perhaps the user should be able to selectively skip tests and warnings.

**Comment by raucao** [comment]
Maybe expressive override keys in the config file?

**Comment by untitaker** [comment]
Yes. I'd say it's only useful in combination with #33 because otherwise errors might pop up in subsequent tests, which you'll also have to skip.

**Comment by untitaker** [comment]
Closing this for now.

**Pull request closed without merging**
