### PR TITLE
Add a new spec checking that the server doesn't return compressed content

### PR DESCRIPTION
**Pull request by gregkare**
Also check that the returned ETags are strong etags

### CODE REVIEW

**Comment by raucao** [comment]
What about this one?

**Comment by gregkare** [comment]
I just merged master into this one, this should be ready to merge if it looks good to you. It's green on the 5apps server

**Comment by raucao** [comment]
> I just merged master into this one

I'm not at all a fan of doing that. Now the history is mixed up. There's even a button for rebase & merge on GitHub now, but a PR as old as this one could/should have been re-opened with linear history IMO.

My question what about this one, btw, was about if this is still relevant. Which is not obvious, as it's been open for so long with no request for review. It looks to me like it is now.

**Comment by gregkare** [comment]
Closed in favor of #47

**Pull request closed without merging**
